from FINAL_PROJ_PART_1 import PART_1_OF_FINAL_PROJECT_CPSC_323
from FINAL_PROJ_PART_2 import  PART_2_OF_FINAL_PROJECT_CPSC_323
from FINAL_PROJ_PART_3 import PART_3_OF_FINAL_PROJECT_CPSC_323

def main():
    PART_1_OF_FINAL_PROJECT_CPSC_323()
    PART_2_OF_FINAL_PROJECT_CPSC_323()
    PART_3_OF_FINAL_PROJECT_CPSC_323()


main()